import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [inputs, setInputs] = useState([{ id: 0, name: "", age: "" }]);

  function onAdd() {
    setInputs([...inputs, { id: inputs.length, name: "", age: "" }]);
  }

  function onChange(e, id) {
    const updatedInputs = inputs.map((input) => {
      if (input.id === id) {
        console.log(e.target.id);
        return { ...input, [e.target.id]: e.target.value };
      }
      return input;
    });
    setInputs(updatedInputs);
  }
  function onDelete(id) {
    setInputs(inputs.filter((input) => input.id !== id));
  }
  function onSubmit() {
    console.log(inputs);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
      </Head>
      <main className="container">
        <h1 className="mb-3">Creador de formularios</h1>
        <div className="row border-top">
          <div className="col-8 mt-4">
            <input className="form-control" />
          </div>
          <div className="col-4 mt-4">
            <button className="btn btn-secondary" onClick={onAdd}>
              Añadir otro +
            </button>
          </div>
        </div>
        <div className="row mt-4 border-top">
          {inputs.map((input) => (
            <div key={input.id} className="col-8">
              <div className="row mt-4">
                <div className="col-2">{input.id}</div>
                <div className="col-4">
                  <input
                    onChange={(e) => onChange(e, input.id)}
                    value={input.name}
                    id="name"
                    className="form-control"
                    placeholder="Nombre"
                  />
                </div>
                <div className="col-4">
                  <input
                    onChange={(e) => onChange(e, input.id)}
                    value={input.age}
                    id="age"
                    className="form-control"
                    placeholder="Edad"
                  />
                </div>
                <div className="col-2">
                  <button
                    onClick={() => onDelete(input.id)}
                    className="btn btn-outline-danger "
                  >
                    Borrar
                  </button>
                </div>
              </div>
            </div>
          ))}

          <div className="col-12 mt-4">
            <button onClick={onSubmit} className="btn btn-primary ">
              Enviar
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
